twig:
  file_name_pattern: '*.twig'
  date:
    timezone: '%env(TIMEZONE)%'
  default_path: '%kernel.project_dir%/templates'
  form_themes: [ 'themes/form.html.twig' ]
  globals:
    supported_locales_string: '%keyroll.supported_locales%'

when@test:
  twig:
    strict_variables: true
