services:
  database:
    container_name: keyroll-database
    image: mariadb:11.4
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost", "-u${DATABASE_USER:-keyroll}", "-p${DATABASE_PASSWORD:-password}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME:-keyroll}
      MARIADB_USER: ${DATABASE_USER:-keyroll}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD:-password}
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-root}
    volumes:
      - keyroll_database:/var/lib/mysql
    networks:
      - keyroll

  keyroll:
    container_name: keyroll
    image: ghcr.io/adrianzech/keyroll:0.0.1
    restart: unless-stopped
    ports:
      - "${KEYROLL_HOST_PORT:-9999}:9000"
    environment:
      APP_ENV: ${APP_ENV:-prod}
      APP_SECRET: ${APP_SECRET:-Sup3rS3cr3t!}
      KEYROLL_DATABASE_HOST: ${DATABASE_HOST:-database}
      KEYROLL_DATABASE_PORT: ${DATABASE_PORT:-3306}
      KEYROLL_DATABASE_NAME: ${DATABASE_NAME:-keyroll}
      KEYROLL_DATABASE_USER: ${DATABASE_USER:-keyroll}
      KEYROLL_DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
    volumes:
      - keyroll_var:/var/www/html/var
    networks:
      - keyroll
    depends_on:
      database:
        condition: service_healthy

volumes:
  keyroll_var:
  keyroll_database:

networks:
  keyroll:
    driver: bridge
